INSERT INTO `mdt_offenses` (`label`, `type`, `category`, `description`, `time`, `fine`, `points`) VALUES
    -- OFFENSES AGAINST PERSONS
    ('Assault', 'misdemeanor', 'OFFENSES AGAINST PERSONS', 'Unlawfully attacking another person.', 30, 1000, 0),
    ('Kidnapping', 'felony', 'OFFENSES AGAINST PERSONS', 'Unlawfully seizing and carrying away a person by force.', 360, 20000, 0),
    ('Manslaughter', 'felony', 'OFFENSES AGAINST PERSONS', 'Killing another person without intention during the commission of a non-felony.', 180, 15000, 0),
    ('Murder', 'felony', 'OFFENSES AGAINST PERSONS', 'Unlawful premeditated killing of one human being by another.', 999, 50000, 0),
    ('Hate Crime', 'felony', 'OFFENSES AGAINST PERSONS', 'A crime motivated by racial, sexual, or other prejudice.', 180, 10000, 0),
    ('Battery', 'misdemeanor', 'OFFENSES AGAINST PERSONS', 'Applying force to another, resulting in harmful or offensive contact.', 60, 3000, 0),
    ('Stalking', 'misdemeanor', 'OFFENSES AGAINST PERSONS', 'Repeatedly following or harassing another person and making threats.', 90, 5000, 0),
    ('Human Trafficking', 'felony', 'OFFENSES AGAINST PERSONS', 'Illegal trade of human beings for the purposes of forced labor or sexual exploitation.', 720, 50000, 0),
    ('Sexual Assault', 'felony', 'OFFENSES AGAINST PERSONS', 'An act in which a person sexually touches another person without their consent.', 360, 20000, 0),
    ('Harassment', 'infraction', 'OFFENSES AGAINST PERSONS', 'Engaging in a pattern of unwanted conduct that alarms or seriously annoys another person, without claiming a legitimate purpose.', 0, 500, 0),

    -- OFFENSES INVOLVING THEFT
    ('Petty Theft', 'misdemeanor', 'OFFENSES INVOLVING THEFT', 'The theft of relatively low value items.', 30, 500, 0),
    ('Grand Theft Auto', 'felony', 'OFFENSES INVOLVING THEFT', 'Theft of an automobile.', 180, 10000, 0),
    ('Burglary', 'felony', 'OFFENSES INVOLVING THEFT', 'Entering a building unlawfully with intent to commit a felony or a theft.', 90, 5000, 0),
    ('Shoplifting', 'misdemeanor', 'OFFENSES INVOLVING THEFT', 'The act of stealing goods from a store.', 30, 1000, 0),
    ('Armed Robbery', 'felony', 'OFFENSES INVOLVING THEFT', 'Robbery with the use of a weapon.', 360, 25000, 0),
    ('Larceny', 'misdemeanor', 'OFFENSES INVOLVING THEFT', 'Unlawful taking of personal property.', 60, 2000, 0),
    ('Embezzlement', 'felony', 'OFFENSES INVOLVING THEFT', 'Theft or misappropriation of funds placed in ones trust or belonging to ones employer.', 180, 15000, 0),
    ('Receiving Stolen Property', 'misdemeanor', 'OFFENSES INVOLVING THEFT', 'Receiving, buying, or possessing property known to be stolen.', 90, 4000, 0),
    ('Identity Theft', 'felony', 'OFFENSES INVOLVING THEFT', 'The fraudulent acquisition and use of a persons private identifying information.', 180, 10000, 0),
    ('Ticket Scalping', 'infraction', 'OFFENSES INVOLVING THEFT', 'Selling tickets for an event without a proper license and often at a rate exceeding the face value.', 0, 200, 0),

    -- OFFENSES INVOLVING FRAUD
    ('Wire Fraud', 'felony', 'OFFENSES INVOLVING FRAUD', 'Fraud involving the use of electronic communications.', 180, 15000, 0),
    ('Insurance Fraud', 'felony', 'OFFENSES INVOLVING FRAUD', 'The act of falsifying or exaggerating the facts of an accident to an insurance company to obtain payment that would not otherwise be made.', 180, 10000, 0),
    ('Securities Fraud', 'felony', 'OFFENSES INVOLVING FRAUD', 'Fraudulent practices in the stock and commodities markets, including insider trading.', 360, 25000, 0),
    ('Credit Card Fraud', 'felony', 'OFFENSES INVOLVING FRAUD', 'Unauthorized use of a credit card to obtain goods of value.', 90, 5000, 0),
    ('Tax Evasion', 'felony', 'OFFENSES INVOLVING FRAUD', 'The illegal nonpayment or underpayment of tax.', 180, 10000, 0),
    ('Healthcare Fraud', 'felony', 'OFFENSES INVOLVING FRAUD', 'Filing dishonest healthcare claims to obtain a profit.', 180, 15000, 0),
    ('Mail Fraud', 'felony', 'OFFENSES INVOLVING FRAUD', 'The use of postal services to commit fraud.', 180, 10000, 0),
    ('Misrepresentation', 'misdemeanor', 'OFFENSES INVOLVING FRAUD', 'Deliberately providing false information in a business transaction.', 90, 3000, 0),
    ('False Advertising', 'misdemeanor', 'OFFENSES INVOLVING FRAUD', 'Advertising products or services in a misleading or deceptive way.', 30, 2000, 0),
    ('Phishing', 'infraction', 'OFFENSES INVOLVING FRAUD', 'Attempting to acquire sensitive information such as usernames, passwords, and credit card details by masquerading as a trustworthy entity in an electronic communication.', 0, 500, 0),

    -- OFFENSES INVOLVING DAMAGE TO PROPERTY
    ('Vandalism', 'misdemeanor', 'OFFENSES INVOLVING DAMAGE TO PROPERTY', 'Deliberately destroying or damaging property.', 30, 1000, 0),
    ('Arson', 'felony', 'OFFENSES INVOLVING DAMAGE TO PROPERTY', 'The criminal act of deliberately setting fire to property.', 360, 20000, 0),
    ('Graffiti', 'misdemeanor', 'OFFENSES INVOLVING DAMAGE TO PROPERTY', 'Writing or drawings scribbled, scratched, or sprayed illicitly on a wall or other surface in a public place.', 60, 2500, 0),
    ('Criminal Mischief', 'misdemeanor', 'OFFENSES INVOLVING DAMAGE TO PROPERTY', 'Intentional or knowing damage to anothers property.', 90, 3000, 0),
    ('Trespassing with Damage', 'misdemeanor', 'OFFENSES INVOLVING DAMAGE TO PROPERTY', 'Entering anothers property without permission and causing damage.', 30, 2000, 0),
    ('Illegal Dumping', 'misdemeanor', 'OFFENSES INVOLVING DAMAGE TO PROPERTY', 'Disposing of waste illegally in non-designated areas.', 90, 5000, 0),
    ('Destruction of Signs', 'infraction', 'OFFENSES INVOLVING DAMAGE TO PROPERTY', 'The act of destroying or defacing road signs or other public signs.', 0, 500, 0),
    ('Littering', 'infraction', 'OFFENSES INVOLVING DAMAGE TO PROPERTY', 'Carelessly discarding trash or other materials on public or private property.', 0, 250, 0),
    ('Damaging Public Utilities', 'felony', 'OFFENSES INVOLVING DAMAGE TO PROPERTY', 'Intentionally damaging or interfering with services of public utility providers.', 180, 10000, 0),
    ('Sabotage', 'felony', 'OFFENSES INVOLVING DAMAGE TO PROPERTY', 'Deliberately destroying, damaging, or obstructing something, especially for political or military advantage.', 360, 25000, 0),

    -- OFFENSES AGAINST PUBLIC ADMINISTRATION
    ('Bribery', 'felony', 'OFFENSES AGAINST PUBLIC ADMINISTRATION', 'Offering, giving, receiving, or soliciting anything of value to influence the actions of an official or other person in charge of a public or legal duty.', 180, 15000, 0),
    ('Perjury', 'felony', 'OFFENSES AGAINST PUBLIC ADMINISTRATION', 'The offense of willfully telling an untruth in a court after having taken an oath or affirmation.', 180, 10000, 0),
    ('Obstruction of Justice', 'felony', 'OFFENSES AGAINST PUBLIC ADMINISTRATION', 'The crime of obstructing prosecutors or other (usually government) officials.', 180, 10000, 0),
    ('Public Corruption', 'felony', 'OFFENSES AGAINST PUBLIC ADMINISTRATION', 'The abuse of public office for private gain.', 360, 25000, 0),
    ('Falsifying Records', 'misdemeanor', 'OFFENSES AGAINST PUBLIC ADMINISTRATION', 'Altering, concealing, falsifying, or destroying a document to obstruct the investigation or other official matters.', 90, 5000, 0),
    ('Witness Tampering', 'felony', 'OFFENSES AGAINST PUBLIC ADMINISTRATION', 'The attempt to alter or prevent the testimony of witnesses within criminal or civil proceedings.', 240, 15000, 0),
    ('Illegal Lobbying', 'misdemeanor', 'OFFENSES AGAINST PUBLIC ADMINISTRATION', 'Lobbying without proper registration or when specifically prohibited.', 120, 8000, 0),
    ('Election Fraud', 'felony', 'OFFENSES AGAINST PUBLIC ADMINISTRATION', 'Illegal interference with the process of an election.', 240, 20000, 0),
    ('Misuse of Public Funds', 'felony', 'OFFENSES AGAINST PUBLIC ADMINISTRATION', 'Using public money for unauthorized, illegal, or unethical purposes.', 180, 15000, 0),
    ('Unauthorized Disclosure of Confidential Information', 'infraction', 'OFFENSES AGAINST PUBLIC ADMINISTRATION', 'Improperly revealing confidential or classified information without authorization.', 0, 1000, 0),

    -- OFFENSES AGAINST PUBLIC ORDER
    ('Disorderly Conduct', 'misdemeanor', 'OFFENSES AGAINST PUBLIC ORDER', 'Engaging in behavior that disrupts public peace, including fighting, making excessive noise, or causing a public disturbance.', 30, 1000, 0),
    ('Illegal Assembly', 'misdemeanor', 'OFFENSES AGAINST PUBLIC ORDER', 'Gathering of people with the intent of engaging in activities that breach public peace or order.', 60, 3000, 0),
    ('Public Intoxication', 'misdemeanor', 'OFFENSES AGAINST PUBLIC ORDER', 'Appearing in public places while significantly impaired by alcohol or drugs, posing a potential danger to self and others.', 0, 500, 0),
    ('Inciting a Riot', 'felony', 'OFFENSES AGAINST PUBLIC ORDER', 'Encouraging, promoting, or participating in violent or disruptive behavior that turns into a mass disturbance.', 90, 7000, 0),
    ('Unlawful Protest', 'misdemeanor', 'OFFENSES AGAINST PUBLIC ORDER', 'Protesting without required permissions or in violation of legal restrictions, potentially leading to public disorder.', 30, 2000, 0),
    ('Loitering', 'infraction', 'OFFENSES AGAINST PUBLIC ORDER', 'Remaining idle in a public place for an extended period without a clear reason, often seen as a nuisance.', 0, 250, 0),
    ('Curfew Violation', 'infraction', 'OFFENSES AGAINST PUBLIC ORDER', 'Failing to adhere to government-imposed curfew regulations, typically enforced to maintain public order during emergencies.', 0, 300, 0),
    ('Vagrancy', 'misdemeanor', 'OFFENSES AGAINST PUBLIC ORDER', 'Living in public spaces without a permanent home or employment, often associated with public nuisance behaviors.', 30, 1000, 0),
    ('Public Nudity', 'misdemeanor', 'OFFENSES AGAINST PUBLIC ORDER', 'Intentionally exposing oneself in a public space, not complying with local decency laws.', 60, 2000, 0),
    ('Illegal Gambling', 'misdemeanor', 'OFFENSES AGAINST PUBLIC ORDER', 'Organizing, participating in, or operating games of chance in public or private settings without legal authorization.', 90, 5000, 0),

    -- OFFENSES AGAINST HEALTH AND MORALS
    ('Drug Possession', 'misdemeanor', 'OFFENSES AGAINST HEALTH AND MORALS', 'Possession of illegal drugs or controlled substances without a prescription.', 60, 2000, 0),
    ('Prostitution', 'misdemeanor', 'OFFENSES AGAINST HEALTH AND MORALS', 'Engaging in, soliciting, or arranging sexual activities in exchange for payment.', 90, 3000, 0),
    ('Illegal Substance Sale', 'felony', 'OFFENSES AGAINST HEALTH AND MORALS', 'Selling or distributing illegal drugs or other prohibited substances.', 180, 10000, 0),
    ('Public Indecency', 'misdemeanor', 'OFFENSES AGAINST HEALTH AND MORALS', 'Performing acts of a sexual nature in public spaces or exposing oneself inappropriately.', 30, 1000, 0),
    ('Gambling Operation', 'felony', 'OFFENSES AGAINST HEALTH AND MORALS', 'Operating or participating in illegal gambling activities, including unlicensed casinos or sports betting.', 180, 15000, 0),
    ('Underage Drinking', 'infraction', 'OFFENSES AGAINST HEALTH AND MORALS', 'Consuming or possessing alcohol by individuals under the legal drinking age.', 0, 500, 0),
    ('Smoking Ban Violation', 'infraction', 'OFFENSES AGAINST HEALTH AND MORALS', 'Smoking in non-smoking areas or violating local smoking regulations.', 0, 250, 0),
    ('Illegal Fireworks', 'misdemeanor', 'OFFENSES AGAINST HEALTH AND MORALS', 'Possessing, using, or selling fireworks without appropriate authorization.', 30, 2000, 0),
    ('Animal Cruelty', 'misdemeanor', 'OFFENSES AGAINST HEALTH AND MORALS', 'Intentionally inflicting harm or failing to provide adequate care to animals.', 90, 5000, 0),
    ('Illegal Tattooing', 'infraction', 'OFFENSES AGAINST HEALTH AND MORALS', 'Tattooing individuals without proper licensing or on minors without legal consent.', 0, 1000, 0),

    -- OFFENSES AGAINST PUBLIC SAFETY
    ('Firearm Possession without Permit', 'felony', 'OFFENSES AGAINST PUBLIC SAFETY', 'Owning or carrying a firearm without the necessary permits.', 180, 10000, 0),
    ('Criminal Possession of Weapon Class A', 'felony', 'OFFENSES AGAINST PUBLIC SAFETY', 'Possession of a Class A weapon, such as a machine gun, assault rifle, or destructive device.', 360, 20000, 0),
    ('Criminal Possession of Weapon Class B', 'felony', 'OFFENSES AGAINST PUBLIC SAFETY', 'Possession of a Class B weapon, such as a sawed-off shotgun or handgun.', 180, 15000, 0),
    ('Criminal Possession of Weapon Class C', 'misdemeanor', 'OFFENSES AGAINST PUBLIC SAFETY', 'Possession of a Class C weapon, such as a rifle or shotgun.', 90, 5000, 0),
    ('Criminal Possession of Weapon Class D', 'misdemeanor', 'OFFENSES AGAINST PUBLIC SAFETY', 'Possession of a Class D weapon, such as a knife or club.', 30, 1000, 0),
    ('Reckless Endangerment', 'felony', 'OFFENSES AGAINST PUBLIC SAFETY', 'Engaging in conduct that poses a significant risk of serious physical injury to others.', 90, 7000, 0),
    ('Traffic Violation', 'infraction', 'OFFENSES AGAINST PUBLIC SAFETY', 'Violating traffic laws such as speeding, running red lights, or illegal parking.', 0, 500, 1),
    ('Illegal Hunting', 'misdemeanor', 'OFFENSES AGAINST PUBLIC SAFETY', 'Hunting wildlife in restricted areas or during off-seasons without proper permits.', 60, 3000, 0),
    ('Building Code Violation', 'misdemeanor', 'OFFENSES AGAINST PUBLIC SAFETY', 'Violating local building regulations, potentially creating safety hazards.', 30, 2000, 0),
    ('DUI with Bodily Injury', 'felony', 'OFFENSES AGAINST PUBLIC SAFETY', 'Driving under the influence of alcohol or drugs and causing bodily harm.', 180, 15000, 3),
    ('Possession of Explosives', 'felony', 'OFFENSES AGAINST PUBLIC SAFETY', 'Illegally possessing or improperly handling explosive materials.', 360, 20000, 0),
    ('Hazardous Waste Dumping', 'felony', 'OFFENSES AGAINST PUBLIC SAFETY', 'Disposing of hazardous materials in a manner that endangers public health and the environment.', 180, 15000, 0),
    ('Negligent Discharge of a Firearm', 'misdemeanor', 'OFFENSES AGAINST PUBLIC SAFETY', 'Accidentally discharging a firearm due to careless handling.', 60, 3000, 0),
    ('Improper Transport of Hazardous Materials', 'felony', 'OFFENSES AGAINST PUBLIC SAFETY', 'Transporting hazardous materials without adhering to safety regulations and legal requirements.', 240, 15000, 0),

    -- OFFENSES INVOLVING THE OPERATION OF A VEHICLE
    ('Driving Without a License', 'misdemeanor', 'OFFENSES INVOLVING THE OPERATION OF A VEHICLE', 'Operating a vehicle without a valid driving license.', 0, 1000, 2),
    ('Driving with a Suspended License', 'misdemeanor', 'OFFENSES INVOLVING THE OPERATION OF A VEHICLE', 'Driving when your drivers license has been suspended or revoked.', 30, 2000, 2),
    ('Hit and Run', 'felony', 'OFFENSES INVOLVING THE OPERATION OF A VEHICLE', 'Leaving the scene of an accident without providing contact information or assisting the injured.', 180, 10000, 3),
    ('Reckless Driving', 'misdemeanor', 'OFFENSES INVOLVING THE OPERATION OF A VEHICLE', 'Driving with a willful disregard for the safety of persons or property.', 60, 3000, 4),
    ('Vehicle Manslaughter', 'felony', 'OFFENSES INVOLVING THE OPERATION OF A VEHICLE', 'Causing the death of another through negligent or reckless driving.', 360, 20000, 0),
    ('Traffic Obstruction', 'infraction', 'OFFENSES INVOLVING THE OPERATION OF A VEHICLE', 'Obstructing traffic flow intentionally or unintentionally.', 0, 500, 0),
    ('Illegal Street Racing', 'misdemeanor', 'OFFENSES INVOLVING THE OPERATION OF A VEHICLE', 'Participating in unauthorized speed contests on public roads.', 90, 5000, 3),
    ('Driving Under the Influence (DUI)', 'felony', 'OFFENSES INVOLVING THE OPERATION OF A VEHICLE', 'Operating a vehicle while under the influence of alcohol or drugs.', 90, 7000, 3),
    ('Failure to Yield', 'infraction', 'OFFENSES INVOLVING THE OPERATION OF A VEHICLE', 'Failing to yield the right of way to other road users where required.', 0, 250, 1),
    ('Driving with Obstructed View', 'infraction', 'OFFENSES INVOLVING THE OPERATION OF A VEHICLE', 'Driving a vehicle with objects blocking the drivers view or control.', 0, 300, 0),

    -- OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE
    ('Illegal Fishing', 'misdemeanor', 'OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE', 'Fishing without a license or in restricted areas.', 30, 2000, 0),
    ('Wildlife Smuggling', 'felony', 'OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE', 'Illegally exporting or importing protected or endangered species.', 360, 25000, 0),
    ('Destroying Habitat', 'felony', 'OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE', 'Deliberate destruction of environments that support wildlife.', 180, 15000, 0),
    ('Poaching', 'felony', 'OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE', 'Illegal hunting, killing, or capturing of wild animals.', 180, 10000, 0),
    ('Illegal Logging', 'felony', 'OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE', 'Unauthorized cutting down of trees in protected areas.', 180, 15000, 0),
    ('Disrupting Wildlife with Noise Pollution', 'misdemeanor', 'OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE', 'Causing noise that can harm wildlife behavior and natural habitat.', 60, 3000, 0),
    ('Feeding Wildlife Illegally', 'infraction', 'OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE', 'Feeding wildlife in areas where it is prohibited by law.', 0, 500, 0),
    ('Illegal Pet Trade', 'felony', 'OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE', 'Engaging in the sale or purchase of wild animals as pets illegally.', 360, 20000, 0),
    ('Use of Harmful Pesticides', 'misdemeanor', 'OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE', 'Using pesticides that are known to cause significant harm to wildlife.', 90, 5000, 0),
    ('Littering in Natural Reserves', 'misdemeanor', 'OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE', 'Disposing of waste in a natural reserve, negatively affecting wildlife.', 30, 2000, 0);