CREATE TABLE IF NOT EXISTS mdt_officers (
  citizenid VARCHAR(255) NOT NULL,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  callsign VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,

  PRIMARY KEY (citizenid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mdt_announcements (
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  message VARCHAR(255) NOT NULL,
  postedBy VARCHAR(255) NOT NULL,
  timestamp VARCHAR(255) NOT NULL,

  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mdt_recent_activities (
  id INT(11) NOT NULL AUTO_INCREMENT,
  category VARCHAR(255) NOT NULL,
  doneBy VARCHAR(255) NOT NULL,
  timestamp VARCHAR(255) NOT NULL,

  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;